name: Setup Copywrite

on:
  workflow_dispatch:

jobs:
  global_replace:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Copywrite
        uses: uses: hashicorp/setup-copywrite@3ace06ad72e6ec679ea8572457b17dbc3960b8ce # v1.0.0

      - name: Check Header Compliance
        run: copywrite headers --plan

